---
- hosts: 192.168.33.16
  user: vagrant
  tasks:
  - name: Collect only facts returned by facter and uptime
    setup:
      fact_path: /etc/ansible/facts.d
      gather_subset:
        - '!all'
        - '!any'
        - facter
  - name: calculate uptime
    command: uptime